#第二种配置方式,端口前面必须加空格.只需要一个,尽量使用.yml了
#server:
  #port: 80
  #context-path: /onyx2

#罩杯
#cupSize: C
#age: 18
#配置文件中使用当前配置
#content: "cupSize: ${cupSize}, age: ${age}"

#第二种配置文件,新建了一个onyxProperties.java类,对应两个属性,对应前面的前缀 prefix
#推荐使用这种方式进行配置.
#onyx:
   #age: 18
   #cupSize: C

#使用dev这个配置,这是总的配置文件.使用下面的dev /product 来区别不同环境的配置文件...
spring:
  profiles:
    #active: dev  开发
    active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydb
    username: root
    password: 123
  jpa:
     hibernate:
       ddl-auto: update  #存在就不管他,表不存在就创建
       #create是项目启动时创建,如果存在就删除再建
       show-sql: true

